=== dominicbosch/msc-liveweb/ws-api-manager/src/json/api-schema.json
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "description": "WebService Plugin Description Schema",
  "type": "object",
  "required": [ "name",  "apiid", "host", "authentication", "packages" ],
  
  "properties": {
    "name": { "type": "string" },
    "apiid": { "type": "string" },
    "host": { "type": "string" },
    "method": { "type": "string" },
    "authentication": {
      "type": "object",
      "oneOf": [
        { "$ref": "#/definitions/int-oauth" },
        { "$ref": "#/definitions/int-api-key" },
        { "$ref": "#/definitions/int-credentials" },
        { "type": "null" }
      ]
    },
    "urlparameters": {
      "type": "object",
      "additionalProperties": {
        "type": "string"
      }
    },
    "packages": { "$ref": "#/definitions/int-packages" }
  },
  "additionalProperties": false,

  "definitions": {
    "int-oauth" : {
      "type": "object",
      "required": [ "oauth" ],
      "properties": {
        "oauth": {
          "type": "object",
          "required": [ "key", "secret" ],
          "properties": {
            "key": { "type": "string" },
            "secret": { "type": "string" }
          },
          "additionalProperties": false
        }
      },
      "additionalProperties": false
    },
    
    "int-api-key" : {
      "type": "object",
      "required": [ "api-key" ],
      "properties": {
        "api-key": {
          "type": "object",
          "required": [ "key" ],
          "properties": {
            "key": { "type": "string" }
          },
          "additionalProperties": false
        }
      },
      "additionalProperties": false
    },
    
    "int-credentials" : {
      "type": "object",
      "required": [ "credentials" ],
      "properties": {
        "credentials": {
          "type": "object",
          "additionalProperties": false
        }
      },
      "additionalProperties": false
    },
    
    "int-packages" : { 
      "type": "object",
      "additionalProperties": {
        "type": "object",
        "required": [ "name", "methods" ],
        "properties": {
          "name":  { "type": "string" },
          "description":  { "type": "string" },
          "methods": { "$ref": "#/definitions/int-methods" }
        },
        "additionalProperties": false
      }
    },
    
    "int-methods" : { 
      "type": "object",
      "additionalProperties": {
        "type": "object",
        "required": [ "name" ],
        "properties": {
          "name":  { "type": "string" },
          "description":  { "type": "string" },
          "parameters":  { "$ref": "#/definitions/int-parameters" }
        },
        "additionalProperties": false
      }
    },
    
    "int-parameters" : {
      "type": "array",
      "items": {
        "type": "object",
        "required": [ "key" ],
        "properties": {
          "key":  { "type": "string" },
          "datatype":  { "type": "string" },
          "optional":  { "type": "boolean" },
          "description":  { "type": "string" }
        },
        "additionalProperties": false
      }
    }
  }
}

=== dominicbosch/msc-liveweb/ws-api-manager/src/json/evernote.json
{
  "name": "Evernote API",
  "apiid": "evernote",
  "host": "sandbox.evernote.com",
  "authentication": {
    "api-key": "",
    "user": "dominicbosch"
  },
  "packages": {
      "NoteStore": {
      "name": "Note store",
      "methods": {
        "createNote": {
          "name": "create note",
          "parameters": [ { "key": "" } ]
        },
        "deleteNode": {
          "name": "delete note",
          "parameters": [ { "key": "" } ]
        },
        "getNote": {
          "name": "get note",
          "parameters": [ { "key": "" } ]
        }
      }
    },
    "UserStore": {
      "name": "User store",
      "methods": {
        "getPublicUserInfo": {
          "name": "get pulic user info",
          "parameters": [ { "key": "" } ]
        },
        "getUser": {
          "name": "get",
          "parameters": [  ]
        }
      }
    }
  }
}

=== dominicbosch/msc-liveweb/ws-api-manager/src/json/probinder.json
{
  "name": "ProBinder API",
  "apiid": "probinder",
  "host": "https://probinder.com/service/",
  "method": "post",
  "authentication": { "credentials": {}},
  "packages": {
    "2": {
      "name": "Content",
      "methods": {
        "addcomment": {
          "name": "add comment",
          "parameters": [ { "key": "" } ]
        },
        "get": {
          "name": "get",
          "parameters": [ { "key": "" } ]
        },
        "setread": {
          "name": "set read",
          "parameters": [ { "key": "" } ]
        }
      }
    },
    "26": {
      "name": "Authentication",
      "methods": {
        "userinfo": { "name": "User Info" },
        "login": {
          "name": "Login",
          "parameters": [ { "key": "" } ]
        }
      }
    },
    "36": {
      "name": "User",
      "methods": {
        "current": {
          "name": "User Info",
          "description": "Retrieves the data of the currently logged in user."
        }
      }
    }
  }
}
